import ClientProvider from "@/components/ClientProvider";
import Header from "@/components/Header";
import PromptInput from "@/components/PromptInput";
import "@/styles/globals.css";
export const metadata = {
  title: "Ai app ",
  description: "Generated by witty",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <ClientProvider>
          <Header />

          <PromptInput />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
